name: Release Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target/
          key: ${{ runner.os }}-cargo-build-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-release-
            ${{ runner.os }}-cargo-build-

      - name: Build release binary
        run: cargo build --release

      - name: Find binary name
        id: binary
        run: |
          # 获取项目名称作为二进制文件名
          BINARY_NAME=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')
          echo "name=$BINARY_NAME" >> $GITHUB_OUTPUT
          echo "Binary name: $BINARY_NAME"

      - name: Verify binary exists
        run: |
          ls -la target/release/
          file target/release/${{ steps.binary.outputs.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.binary.outputs.name }}-linux-x64
          path: target/release/${{ steps.binary.outputs.name }}
          retention-days: 30
